install:
  - ps: Start-FileDownload "https://raw.githubusercontent.com/carllerche/travis-rust-matrix/master/install.ps1"; . .\install.ps1

platform:
  - x86
  - x64

environment:
  matrix:
    - RUST_VERSION: 1.8.0
    - RUST_VERSION: beta
    - RUST_VERSION: alpha

build: false

test_script:
  - cargo build --verbose
  - cargo test --verbose
