install:
  - ps: Start-FileDownload "https://raw.githubusercontent.com/carllerche/travis-rust-matrix/master/install.ps1"; . .\install.ps1

environment:
  matrix:
    - RUST_VERSION: 1.14.0
    - RUST_VERSION: beta
    - RUST_VERSION: nightly

matrix:
  allow_failures:
    - RUST_VERSION: nightly

build: false

test_script:
  - cargo build --verbose
  - cargo test --verbose
